### ISSUE TITLE
build docs

### ISSUE THREAD

**Issue by brendangregg** [wkz/ply#1]
I got this far:

```
./autogen.sh
./configure
make
```

But then it can't find bpf.h:

```
root@bgregg-build-i-xxxxxxxx:/mnt/src/ply# make
Making all in src
make[1]: Entering directory `/mnt/src/ply/src'
make  all-am
make[2]: Entering directory `/mnt/src/ply/src'
  CC       lang/ply-parse.o
In file included from lang/parse.y:25:0:
lang/ast.h:29:23: fatal error: linux/bpf.h: No such file or directory
compilation terminated.
make[2]: *** [lang/ply-parse.o] Error 1
make[2]: Leaving directory `/mnt/src/ply/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/mnt/src/ply/src'
make: *** [all-recursive] Error 1
```

I have linux/bpf.h in my kernel build directory, and it's also under /lib/modules/`uname -r`/source/include

But it isn't under /usr/include. And "make headers_install" doesn't put it there...

**Comment by wkz** [comment]
Well that's disapointing :smile: 

I should probably add a `--with-kdir` or similar.

As a workaround in the mean time:

`CFLAGS="-I /path/to/kernel/include" ./configure`

should do the trick.

**Comment by brendangregg** [comment]
thanks, getting further!:

```
root@bgregg-build-i-xxxxxxxx:/mnt/src/ply# CFLAGS="-I /lib/modules/`uname -r`/source/include" ./configure^C
root@bgregg-build-i-xxxxxxxx:/mnt/src/ply# make
Making all in src
make[1]: Entering directory `/mnt/src/ply/src'
make  all-am
make[2]: Entering directory `/mnt/src/ply/src'
  CC       lang/ply-parse.o
In file included from /lib/modules/4.5.0-rc2-virtual+/source/include/uapi/linux/bpf.h:10:0,
                 from /lib/modules/4.5.0-rc2-virtual+/source/include/linux/bpf.h:10,
                 from lang/ast.h:29,
                 from lang/parse.y:25:
/lib/modules/4.5.0-rc2-virtual+/source/include/linux/types.h:14:26: error: conflicting types for ‘fd_set’
 typedef __kernel_fd_set  fd_set;
                          ^
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:219:0,
                 from /usr/include/stdlib.h:314,
                 from lang/ast.h:26,
                 from lang/parse.y:25:
/usr/include/x86_64-linux-gnu/sys/select.h:75:5: note: previous declaration of ‘fd_set’ was here
   } fd_set;
[...]
```

**Comment by wkz** [comment]
Ahh, right you're getting kernel headers included in your build. Try:

`CFLAGS="-I /path/to/kernel/include/uapi" ./configure`

**Comment by brendangregg** [comment]
Then it complains about:

```
/lib/modules/4.5.0-rc2-virtual+/source/include/uapi/linux/stddef.h:1:28: fatal error: linux/compiler.h: No such file or directory
```

So if I do this:

```
CFLAGS="-I /lib/modules/`uname -r`/source/include/uapi -I /lib/modules/`uname -r`/source/include" ./configure
make
[...]
bpf-syscall.c: In function ‘bpf_prog_load’:
bpf-syscall.c:54:17: error: ‘__NR_bpf’ undeclared (first use in this function)
  return syscall(__NR_bpf, BPF_PROG_LOAD, &attr, sizeof(attr));
                 ^
bpf-syscall.c:54:17: note: each undeclared identifier is reported only once for each function it appears in
bpf-syscall.c: In function ‘bpf_map_create’:
bpf-syscall.c:70:17: error: ‘__NR_bpf’ undeclared (first use in this function)
  return syscall(__NR_bpf, BPF_MAP_CREATE, &attr, sizeof(attr));
                 ^
bpf-syscall.c: In function ‘bpf_map_op’:
bpf-syscall.c:84:17: error: ‘__NR_bpf’ undeclared (first use in this function)
  return syscall(__NR_bpf, cmd, &attr, sizeof(attr));
```

more progress!

So if I try:

```
CFLAGS="-I /lib/modules/`uname -r`/source/include/uapi -I /lib/modules/`uname -r`/source/include -I /lib/modules/`uname -r`/source/include/uapi/asm-generic" ./configure
make
[...]
ply.h:34:50: error: ‘errno’ undeclared (first use in this function)
 #define _pe(_fmt, ...) _e("errno:%d " _fmt "\n", errno, ##__VA_ARGS__)
```

missing errno?

**Comment by wkz** [comment]
Gosh, this is broken beyond belief! Thanks for sticking with it.

I pushed a commit which includes the proper header.

**Comment by wkz** [comment]
Btw what distro are you on? Seems I have some work to do :smile:

**Comment by brendangregg** [comment]
ubuntu trusty, with a new linux 4.5 kernel dropped in (maybe badly), which has Alexei's new stack trace BPF stuff....

**Comment by brendangregg** [comment]
Still having trouble with errno:

```
CFLAGS="-I /lib/modules/`uname -r`/source/include/uapi -I /lib/modules/`uname -r`/source/include -I /lib/modules/`uname -r`/source/include/uapi/asm-generic" ./configure
[...]
lang/lex.c:687:3: error: ‘errno’ undeclared (first use in this function)
```

**Comment by wkz** [comment]
Now that's just wierd, flex includes errno.h in the generated output (src/lang/lex.c:22).

**Comment by wkz** [comment]
I can reproduce the error if I use the same CFLAGS magic as you do. It seems to mess up some include order somewhere.

Perhaps we should try to get `linux/bpf.h` and `linux/bpf_common.h` into your `/usr/include` instead.

Just as a hack, could you try to copy them in there manually?

**Comment by wkz** [comment]
Ok, intresting find, by using `CPPFLAGS` instead of `CFLAGS` my system will build successfully.

It puts the includes slightly earlier in the gcc invokation. Does that work for you?

PS. It is now 3 AM over here so I need to get some sleep :smile: I will check back tomorrow to see if you managed to get it working.

**Comment by wkz** [comment]
I added a `--with-kerneldir=DIR` option to configure. When used, it will do a `headers_install` to an internal directory which is then added to the include path during build.

Does that work for you?

**Comment by brendangregg** [comment]
Yes, thanks, so my steps are now:

### Ubuntu install, 1-Mar-2016

```
git clone https://github.com/wkz/ply
cd ply
./autogen.sh
./configure --with-kerneldir=/lib/modules/`uname -r`/source
make
make install
```

This should be copied into install docs somewhere.

**Comment by wkz** [comment]
Great, thanks for your patience!

I added a section to the README.md, describing it. See 403eb66
