### ISSUE TITLE
build ply for arm64 target 

### ISSUE THREAD

**Issue by maindoor** [wkz/ply#18]
Hi,
I'm trying to build ply for arm64 target but somehow I'm unable to do it:
I used configure like this:
./configure --target=arm64 --with-kerneldir=/home/kedaru/proj/base/linux/

But I still get x86_64 ply file after a make. How do I compile ply executable for arm64 target ?

Thanks.

**Comment by wkz** [comment]
Ah yes, one could easily think that `--target=` would be used for this purpose. The option you're looking for is `--host=`. Also you need to specify your full compiler prefix, so typically something like `--host=aarch64-unknown-linux-gnueabi`

Have a look here for more information on automake and cross-compilation:

https://www.gnu.org/software/automake/manual/html_node/Cross_002dCompilation.html
