### ISSUE TITLE
ply one-liners

### ISSUE THREAD

**Issue by brendangregg** [wkz/ply#2]
Doesn't seem that ply can be used at the command line yet. Eg, something like:

```
ply -e 'kprobe:SyS_execve { printf("running: %s", arg(1)); }'
```

**Comment by wkz** [comment]
The option for a literal probe is `-c`. I chose it based on `sh(1)`, maybe `-e`is more logical.

**Comment by wkz** [comment]
Although, things like converting user-space pointers into strings is nowhere near supported yet. Toy, remember? :smile: 

Other than the stuff in the manual, expect _nothing_ :smile:

**Comment by brendangregg** [comment]
ok, thanks, -c works.
