### ISSUE TITLE
help writing a program using ply

### ISSUE THREAD

**Issue by maindoor** [wkz/ply#20]
Hi,
I am able to trigger a print on a kprobe entering into a function.
At an offset into one of the arguments to a function there is a Mac-address.
How do I trigger a print only if the Mac-address matches a certain value ?
eg. if ((arg2+33)[0] == 0xab && (arg2+33)[1] == 0xcd )
         printf("%v\n", stack());

Thanks.

**Comment by hubgitname** [comment]
If you read the manual at https://wkz.github.io/ply/ply.1.html
it talks about predicate and control of flow, have you tried that ?

**Comment by maindoor** [comment]
@hubgitname Can you give me some examples ? how can I format arg1 as a u32 ? 
Just more examples on the documentation would be helpful, how can I find out what other features
are in the Little Language ?

**Comment by maindoor** [comment]
https://www.linaro.org/blog/kprobes-event-tracing-armv8/
This page has a nice way of referencing arguments, I just want to know if ply has an interface to access the arguments. eg: cat > kprobe_events <<EOF
p:wait_p do_wait wo_type=+0(%x0):u32 wo_flags=+4(%x0):u32

If I can't do this with ply pls let me know and I can close this entry.

**Comment by wkz** [comment]
This it not possible at the moment, sorry. The next features going in are going to be the subscript operator and casts.

**Comment by maindoor** [comment]
Thanks for clarifying. It would be great if ply can access those variables and arguments, gives complete
probe capabilities. I will close this bug.
