### ISSUE TITLE
ply in QEMU: error: unable to create map 'stdbuf', errno:38

### ISSUE THREAD

**Issue by jgsun** [wkz/ply#24]
Hi Sir

I tried to run ply in QEMU aarch64, but I met failure error: unable to create map 'stdbuf', errno:38, would you please help with it?

root@/lib# uname -a
Linux qemu-aarch64 5.6.11 #34 SMP Thu Oct 8 20:01:26 CST 2020 aarch64 GNU/Linux

root@/lib# cat opensoop.ply 
#!/usr/bin/env ply

kprobe:do_sys_open
{
    printf("%v(%v): %s\n",
           comm, pid, str(arg1));
}

root@/lib# ./opensoop.ply 
info: creating kallsyms cache
error: unable to create map 'stdbuf', errno:38
ERR:-38
root@/lib# ply -h
ply - Dynamic tracing utility

Usage:
  ply [options] <ply-text>
  ply [options] <ply-file>

Options:
  -c COMMAND     Run COMMAND in a shell, exit upon completion.
  -d             Enable debug output.
  -e             Exit after compiling.
  -h             Print usage message and exit.
  -k             Keep going in face of trace buffer overruns.
  -S             Show generated BPF.
  -v             Print version information.

root@/lib# ply -v
ply 7ce38a7e73-dirty (linux-version:267277~4.20.13)

**Comment by wkz** [comment]
Usually it means that your kernel is missing `CONFIG_BPF_SYSCALL`. Have a look at https://github.com/wkz/sysroot/blob/master/aarch64-kernel.config and check for any diff in BPF related settings.

**Comment by jgsun** [comment]
Many thanks@wkz.

I fixed kernel config issue. but met new issue as below： 

root@~# ./opensnoop.ply 
error: unable to load kprobe:do_sys_open, errno:22
error: no output from kernel bpf verifier, retry with debugging enabled
ERR:-22

```
root@~# zcat /proc/config.gz | grep BPF
# CONFIG_CGROUP_BPF is not set
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_ARCH_WANT_DEFAULT_BPF_JIT=y
# CONFIG_NETFILTER_XT_MATCH_BPF is not set
# CONFIG_BPFILTER is not set
# CONFIG_NET_CLS_BPF is not set
# CONFIG_BPF_JIT is not set
CONFIG_HAVE_EBPF_JIT=y
# CONFIG_TEST_BPF is not set
```

**Comment by wkz** [comment]
I can't reproduce your issue in my test environment. I would guess you're missing more kernel config parameters. In the ply repo, if you go to the test directory and run:

    make aarch64-check-install-tc
    make aarch64-shell

You will be dropped in to a QEMU instance where you can verify that your script works. From there I would start to diff any parameters having to do with either kprobes or BPF.

**Comment by jgsun** [comment]
Just now, I enabled kernel ftrace, the error changed to:

root@~# ./opensnoop.ply 
ERR:-13

what's the meaning of this err code?

**Comment by jgsun** [comment]
jgsun@VirtualBox:~/repo/ply$ errno 13
EACCES 13 Permission denied

Now I am the root user, should have permission, why?
 Thanks!

**Comment by wkz** [comment]
No idea. I would start by looking at which syscall returns the error (with `strace`).

**Comment by jgsun** [comment]
Great idea, strace it then you will get the details!

```
openat(AT_FDCWD, "/sys/kernel/debug/tracing/kprobe_events", O_RDWR|O_CREAT|O_APPEND, 0666) = -1 EACCES (Permission denied)
close(10)                               = 0
close(5)                                = 0
munmap(0x7fad6ba000, 1733056)           = 0
close(4)                                = 0
fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(0xcc, 0x40), ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "ERR:-13\n", 8ERR:-13
)                = 8
exit_group(1)                           = ?
+++ exited with 1 +++
```

From the above, I enabled kconfig CONFIG_KRPOBE=y, now the ply works well:
```
root@~# ./opensnoop.ply 
ply: active
sh             (  145): /root/.ash_history
ls             (  148): /etc/ld.so.cache
ls             (  148): /lib64/tls/aarch64/libresolv.so.2
ls             (  148): /lib64/tls/libresolv.so.2
ls             (  148): /lib64/aarch64/libresolv.so.2
ls             (  148): /lib64/libresolv.so.2
ls             (  148): /lib64/libc.so.6
ls             (  148): .
sh             (  145): /etc/passwd
sh             (  145): /root/.ash_history
sync           (  149): /etc/ld.so.cache
sync           (  149): /lib64/tls/aarch64/libresolv.so.2
sync           (  149): /lib64/tls/libresolv.so.2
sync           (  149): /lib64/aarch64/libresolv.so.2
sync           (  149): /lib64/libresolv.so.2
sync           (  149): /lib64/libc.so.6
sh             (  145): /etc/passwd
```

A simple summary:
To use ply, we need enable kconfig(BPF_SYSCALL, KPROBES and FTRACE) and mound debugfs by `mount -t debugfs nodev /sys/kernel/debug`
```
CONFIG_KPROBES=y
CONFIG_HAVE_DYNAMIC_FTRACE=y
CONFIG_HAVE_DYNAMIC_FTRACE_WITH_REGS=y
CONFIG_HAVE_FTRACE_MCOUNT_RECORD=y
CONFIG_FTRACE=y
CONFIG_DYNAMIC_FTRACE=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
```

I think we can close this issue, thanks for your great help! @wkz
