### ISSUE TITLE
What's the reason about this error: syntax error, unexpected IDENT, expecting ')' ?

### ISSUE THREAD

**Issue by zhaoyuxing18** [wkz/ply#30]
I want to trace kernel struct and derenference some elements and I've tried the following：
cat test.ply
#!/sbin/ply

#include <net/sock.h>

kprobe:tcp_set_state
{
        printf("%v %v %v %v\n", pid, comm, str(((struct sock *)arg0)->sk_state), arg1);
}

but there's an error:
![image](https://user-images.githubusercontent.com/75468747/109609123-df1c0180-7b65-11eb-9f25-242cba26d102.png)

**Comment by wkz** [comment]
It would be great if your example worked, alas you are trying to do multiple things that are currently not supported by ply:

- There is no support to parse C code.
- The cast operator is not implemented yet.
